spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.10.149:1433;DatabaseName=ykt
    username: sa
    password: 123
    validationQuery: SELECT 1
    max-active: 100
    min-idle: 10
    max-wait: 10000
epc:
  gatewayId: MJ
  gcId: 4202020700
  subsystem: mjgl/
  threadNum: 1
