#广场ID及GatewayId（甩项）
epc:
  gatewayId: MJ
  gcId: 4401830001
  subsystem: mjgl/
  threadNum: 1
mj:
  serverIP: 127.0.0.1

spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=netking
    username: sa
    password: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
AcssDoorOpenUrl: http://192.168.1.100:8011/AcssDoorOpen?s_key=D41D8CD98F00B204E9800998ECF8427E&userno=0001000343
