#广场ID及GatewayId
epc:
  gatewayId: MJ
  gcId: 3601130010
  subsystem: mjgl/
  threadNum: 5
#门禁请求子系统接口
access:
  #门禁开门
  doorOpenUrl: http://192.168.9.159:3500/api.aspx/acss.door.open.directly
  #门禁门状态列表
  doorStatusUrl: http://192.168.9.159:3500/api.aspx/acss.door.state.list
  #签名密钥
  secret: 71cfa1c59773ddfa289994e6d505bba3

