spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.71.16.131:1433;DatabaseName=carsafe
    username: sa
    password: feiyang2A@
    validationQuery: SELECT 1
    max-active: 100
    min-idle: 10
    max-wait: 10000
epc:
  gatewayId: MJ
  gcId: 3506811020
  subsystem: mjgl/
  threadNum: 1
