spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.26.58.188:1433;DatabaseName=carsafe
    username: sa
    password: 231584
    validationQuery: SELECT 1
    max-active: 100
    min-idle: 10
    max-wait: 10000
epc:
  gatewayId: MJ
  gcId: 4419001220
  subsystem: mjgl/
  threadNum: 1
AcssDoorOpenUrl: http://192.168.1.100:8011/AcssDoorOpen?s_key=D41D8CD98F00B204E9800998ECF8427E&userno=0001000343
