#广场ID及GatewayId
epc:
  gatewayId: MJ
  gcId: 1101050001
  subsystem: mjgl/
  threadNum: 5
#门禁请求子系统接口
access:
  # 获取用户uuid
  userInfoUrl: http://10.1.219.14/openapi/service/base/user/getDefaultUserUuid
  # 分页获取门禁点
  doorsUrl: http://10.1.219.14/openapi/service/acs/res/getDoors
  # 获取门禁状态
  doorStatusUrl: http://10.1.219.14/openapi/service/acs/status/getDoorStatusByUuids
  # 获取门禁事件状态
  doorEventsUrl: http://10.1.219.14/openapi/service/acs/event/getDoorEventsHistory
  #同步反控门禁点
  syncContolUrl: http://10.1.219.14/openapi/service/acs/control/synControl
  appKey: 9b6ca981
  secret: 532fd3a393444ab09093cecb6c7ba036
