server:
  port: 18200
mqtt:
  hostUrl: tcp://127.0.0.1:1883
  username: admin
  password: wanda@1234
  client-id: IOT-EPC-MJ
  cleanSession: true
  reconnect: true
  keepAlive: 100
  isOpen: true
  qos: 1

spring:
  #redis配置
  redis:
    host: 127.0.0.1
    port: 16379
    password:

beanName: carsafeControlDevice

epc:
  gatewayId: MJ
  #需修改 项目id去掉pj
  gcId: 6104230010
  subsystem: mjgl/
  threadNum: 5
#需修改 门禁请求子系统接口
access:
  #门禁开门
  doorOpenUrl: http://192.168.5.10:9022/api.aspx/acss.door.open
  #门禁门状态列表
  doorStatusUrl: http://192.168.5.10:9022/api.aspx/acss.door.state.list
  #签名密钥
  secret: 123456
  #操作用户编号
  userNo: '0001000154'
