server:
  port: 9400
beanName: daHuaDoorDevice
mqtt:
  hostUrl: tcp://127.0.0.1:1883
  username: admin
  password: wanda@1234
  client-id: IOT-EPC-MJ
  cleanSession: true
  reconnect: true
  keepAlive: 100
  isOpen: true
  qos: 1
spring:
  redis:
    host: 127.0.0.1
    port: 16379
    password:
epc:
  gatewayId: MJ
  gcId: 2024000480
  subsystem: mj/
  threadNum: 1
  cron: 0 0/1 * * * ?
#  一个控制器有几个门
  channelId: 2

m_nPort: 37777
m_strUser: admin
m_strPassword: LHWD1234
